
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 500

test:
  adapter: sqlite3
  database: db/test.sqlite3 #":memory:"
  timeout: 500

production:
  adapter: postgresql
  encoding: unicode
  host: postgresql
  database: railsapi_production
  username: railsapi
  password: 123456
  pool: 5
  timeout: 500